=== redeskako/EjemplosJ2SE/alef/UNED_2016/J2EE/HolaMundoUned/WebContent/Biblioteca.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo,autor)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>

=== redeskako/EjemplosJ2SE/alef/UNED_2016/J2EE/HolaMundoUned/WebContent/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BibliotecaFormato.xsl"?>
<!DOCTYPE libros PUBLIC "//UNKNOWN/" "Biblioteca.dtd">
<libros>
	<libro>
		<titulo>Tutorial html</titulo>
		<autor>El jefe del html</autor>
	</libro>
	<libro>
		<titulo>Tutorial css</titulo>
		<autor>El jefe del css</autor>
	</libro>
	<libro>
		<titulo>Tutorial javascript</titulo>
		<autor>El jefe del javascript</autor>
	</libro>
	<libro>
		<titulo>Tutorial java</titulo>
		<autor>El jefe del java</autor>
	</libro>
	<libro>
		<titulo>Tutorial xml</titulo>
		<autor>El jefe del xml</autor>
	</libro>
</libros>
